#!/bin/bash
# Command for running neovim

if [[ "$1" = /* ]]; then
  file_name="$(basename ${1})"
  dir_name="$(dirname ${1})"
else
  file_name="$1"
  dir_name="$(pwd)"
fi

# Name container by tmux session
name=$(tmux display-message -p '#S')
timestamp=$(date +%s)

# Run the docker command
docker run -i -t -P -v "$dir_name":/src --name "nvim_${name}_${timestamp}" thornycrackers/neovim /bin/bash -c "cd /src; nvim $file_name"

# Remove container after it's done
docker rm $(docker ps -l -q)